### PR TITLE
Fix typos in README

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by kaalleen** [comment]
Would you mind to request these changes over in https://github.com/EmbroidePy/pyembroidery ?
We can then pull them into our fork later.

**Comment by luzpaz** [comment]
@kaalleen sure!  
Opened upstream PR https://github.com/EmbroidePy/pyembroidery/pull/155

**Comment by luzpaz** [comment]
Upstream merged commit in https://github.com/EmbroidePy/pyembroidery/commit/6fd941f4b2cf65b40addeb91bad66d87fc924696

**Comment by kaalleen** [comment]
Thanks :)

**Pull request closed without merging**
